name: syncfusion_flutter_calendar
description: The Flutter Calendar widget has nine built-in configurable views that provide basic functionalities for scheduling and representing appointments/events efficiently.
version: 18.3.35
homepage: https://github.com/syncfusion/flutter-examples

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  timezone: 0.8.0
  syncfusion_flutter_core:
    git:
      url: https://SyncfusionBuild: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@github.com/essential-studio/flutter-core
      path: syncfusion_flutter_core
      branch: hotfix/20.1.0.47_Vol1
      ref: hotfix/20.1.0.47_Vol1

  syncfusion_flutter_datepicker:
    git:
      url: https://SyncfusionBuild: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@github.com/essential-studio/flutter-datepicker
      path: flutter_datepicker/syncfusion_flutter_datepicker
      branch: hotfix/20.1.0.47_Vol1
      ref: hotfix/20.1.0.47_Vol1

  intl: ">=0.15.0 <0.20.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/timezone/data/2020a.tzf