name: syncfusion_localizations
description: Syncfusion Localizations package contains localized text for 77 cultures for all the applicable Syncfusion Flutter Widgets. 
version: 18.3.35-nullsafety
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_localizations

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.15.0 <0.20.0"
  syncfusion_flutter_core:
    git:
      url: https://SyncfusionBuild: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@github.com/essential-studio/flutter-core
      path: syncfusion_flutter_core
      branch: hotfix/20.1.0.47_Vol1
      ref: hotfix/20.1.0.47_Vol1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
