name: syncfusion_flutter_pdfviewer
description: Flutter PDF Viewer library is used to display a PDF document seamlessly and efficiently.
version: 18.3.35-beta
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_pdfviewer

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.

  plugin:
    platforms:
      android:
        package: com.syncfusion.flutter.pdfviewer
        pluginClass: SyncfusionFlutterPdfViewerPlugin
      ios:
        pluginClass: SyncfusionFlutterPdfViewerPlugin
      web:
        default_package: syncfusion_pdfviewer_web
      macos:
        default_package: syncfusion_pdfviewer_macos
      windows:
        default_package: syncfusion_pdfviewer_windows

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.0
  async: ^2.5.0
  http: ^0.13.0
  uuid: ^3.0.5

  syncfusion_pdfviewer_platform_interface:
    git:
      url: https://SyncfusionBuild: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@github.com/essential-studio/flutter-pdfviewer
      path: flutter_pdfviewer/syncfusion_pdfviewer_platform_interface
      branch: hotfix/20.1.0.47_Vol1
      ref: hotfix/20.1.0.47_Vol1

  syncfusion_pdfviewer_web:
    git:
      url: https://SyncfusionBuild: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@github.com/essential-studio/flutter-pdfviewer
      path: flutter_pdfviewer/syncfusion_pdfviewer_web
      branch: hotfix/20.1.0.47_Vol1
      ref: hotfix/20.1.0.47_Vol1

  syncfusion_pdfviewer_macos:
    git:
      url: https://SyncfusionBuild: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@github.com/essential-studio/flutter-pdfviewer
      path: flutter_pdfviewer/syncfusion_pdfviewer_macos
      branch: hotfix/20.1.0.47_Vol1
      ref: hotfix/20.1.0.47_Vol1
  
  syncfusion_pdfviewer_windows:
    git:
      url: https://SyncfusionBuild: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@github.com/essential-studio/flutter-pdfviewer
      path: flutter_pdfviewer/syncfusion_pdfviewer_windows
      branch: hotfix/20.1.0.47_Vol1
      ref: hotfix/20.1.0.47_Vol1

  syncfusion_flutter_core:
    git:
      url: https://SyncfusionBuild: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@github.com/essential-studio/flutter-core
      path: syncfusion_flutter_core
      branch: hotfix/20.1.0.47_Vol1
      ref: hotfix/20.1.0.47_Vol1

  syncfusion_flutter_pdf:
    git:
      url: https://SyncfusionBuild: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@github.com/essential-studio/flutter-pdf
      path: flutter_pdf/syncfusion_flutter_pdf
      branch: hotfix/20.1.0.47_Vol1
      ref: hotfix/20.1.0.47_Vol1

dev_dependencies:
  flutter_test:
    sdk: flutter